In [ ]:
import numpy as np

In [ ]:
a = np.array([23,45,67,34,56,90])
print(a)
print(a[3])
print(a[2:6])
print(a[5:])
print(a[:6])


[23 45 67 34 56 90]
34
[67 34 56 90]
[90]
[23 45 67 34 56 90]


In [ ]:
b = np.array([[34,56,78,89] ,[34,56,78,23,45], [34,67,23,98,43]])

<ipython-input-14-6bd4535b9c84>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b = np.array([[34,56,78,89] ,[34,56,78,23,45], [34,67,23,98,43]])


In [ ]:
# c = np.array([[34,56,78,89] ,[34,56,78,23,45], [34,67,23,98,43]]) + np.array([23,45,67,34,56,90])

a =np.array([23,45,67,89])
b =np.array([1,2,3,4])
z = np.concatenate((a,b))
print(z)
#print(a + b)

[23 45 67 89  1  2  3  4]


In [ ]:
a = np.array([[1,2,3,4], [2,4,5,6]])
b = np.array([[10,11,12,13],[21,22,23,24]])
c = np.concatenate((a,b), axis=1)
print(c)
for i in a:
  print(a)

[[ 1  2  3  4 10 11 12 13]
 [ 2  4  5  6 21 22 23 24]]
[2 4 5 6]
[2 4 5 6]


In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,2,9]])
print(b[2,1])
print(b[1,0:2])
for i in b:
  for j in i:
    print(j)

2
[4 5]
1
2
3
4
5
6
7
2
9


In [ ]:
b =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
#print(b[1,1,2])
#print(b[0,0:2])
#print(b[1,1:2])
#print(b[0,1,1:2])
#print(b[1,0,1:3])
#np.sort(b)
for i in b:
  for j in i:
    for k in j:
      print(k)


1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
b = np.array([1,2,3,4,5,6])
#print(b[1:3])
for i in b:
  print(i)

1
2
3
4
5
6
